// Complete seed data with all businesses having full details
export const COMPLETE_MOCK_BUSINESSES = [
  {
    id: 'org_shoreditch_plumbing',
    name: 'Shoreditch Plumbing Services',
    email: 'info@shoreditchplumbing.co.uk',
    phone: '+44 20 7123 4567',
    categories: ['plumbing', 'general_handyman'],
    service_radius_miles: 5,
    location: {
      address: '15 Old Street',
      city: 'London',
      state: 'Greater London',
      zip: 'EC1V 9HL',
      coordinates: { latitude: 51.5254, longitude: -0.0877 },
    },
    accepts_new_requests: 1,
    total_completed: 247,
    response_time_avg_minutes: 45,
    opening_hours: {
      monday: { open: '08:00', close: '18:00', isOpen: true },
      tuesday: { open: '08:00', close: '18:00', isOpen: true },
      wednesday: { open: '08:00', close: '18:00', isOpen: true },
      thursday: { open: '08:00', close: '18:00', isOpen: true },
      friday: { open: '08:00', close: '18:00', isOpen: true },
      saturday: { open: '09:00', close: '14:00', isOpen: true },
      sunday: { isOpen: false },
    },
    availability_status: 'available',
    years_in_business: 12,
    is_insured: 1,
    is_verified: 1,
    description: 'Professional plumbing and general handyman services in East London. Specializing in emergency repairs, installations, and maintenance.',
    website: 'https://shoreditchplumbing.co.uk',
  },
  {
    id: 'org_eastlondon_electrical',
    name: 'East London Electrical Ltd',
    email: 'contact@eastlondonelectrical.com',
    phone: '+44 20 7234 5678',
    categories: ['electrical', 'appliance_repair'],
    service_radius_miles: 7,
    location: {
      address: '42 City Road',
      city: 'London',
      state: 'Greater London',
      zip: 'EC1Y 2AP',
      coordinates: { latitude: 51.5268, longitude: -0.0871 },
    },
    accepts_new_requests: 1,
    total_completed: 189,
    response_time_avg_minutes: 60,
    opening_hours: {
      monday: { open: '07:30', close: '19:00', isOpen: true },
      tuesday: { open: '07:30', close: '19:00', isOpen: true },
      wednesday: { open: '07:30', close: '19:00', isOpen: true },
      thursday: { open: '07:30', close: '19:00', isOpen: true },
      friday: { open: '07:30', close: '19:00', isOpen: true },
      saturday: { open: '08:00', close: '16:00', isOpen: true },
      sunday: { isOpen: false },
    },
    availability_status: 'available',
    years_in_business: 8,
    is_insured: 1,
    is_verified: 1,
    description: 'Certified electricians serving East London. From rewiring to appliance repairs, we handle all electrical needs safely and efficiently.',
    website: 'https://eastlondonelectrical.com',
  },
  {
    id: 'org_shoreditch_hvac',
    name: 'Shoreditch HVAC & Heating',
    email: 'hello@shoreditchhvac.co.uk',
    phone: '+44 20 7345 6789',
    categories: ['hvac'],
    service_radius_miles: 10,
    location: {
      address: '78 Great Eastern Street',
      city: 'London',
      state: 'Greater London',
      zip: 'EC2A 3JL',
      coordinates: { latitude: 51.5244, longitude: -0.0811 },
    },
    accepts_new_requests: 1,
    total_completed: 156,
    response_time_avg_minutes: 90,
    opening_hours: {
      monday: { open: '08:00', close: '17:00', isOpen: true },
      tuesday: { open: '08:00', close: '17:00', isOpen: true },
      wednesday: { open: '08:00', close: '17:00', isOpen: true },
      thursday: { open: '08:00', close: '17:00', isOpen: true },
      friday: { open: '08:00', close: '17:00', isOpen: true },
      saturday: { isOpen: false },
      sunday: { isOpen: false },
    },
    availability_status: 'busy', // Currently busy
    years_in_business: 15,
    is_insured: 1,
    is_verified: 1,
    description: 'Heating, ventilation, and air conditioning specialists. Gas Safe registered with 15 years of experience in commercial and residential HVAC systems.',
    website: 'https://shoreditchhvac.co.uk',
  },
  {
    id: 'org_tech_city_carpentry',
    name: 'Tech City Carpentry & Joinery',
    email: 'bookings@techcitycarpentry.com',
    phone: '+44 20 7456 7890',
    categories: ['carpentry'],
    service_radius_miles: 6,
    location: {
      address: '23 Leonard Street',
      city: 'London',
      state: 'Greater London',
      zip: 'EC2A 4QS',
      coordinates: { latitude: 51.5243, longitude: -0.0823 },
    },
    accepts_new_requests: 1,
    total_completed: 134,
    response_time_avg_minutes: 120,
    opening_hours: {
      monday: { open: '07:00', close: '16:00', isOpen: true },
      tuesday: { open: '07:00', close: '16:00', isOpen: true },
      wednesday: { open: '07:00', close: '16:00', isOpen: true },
      thursday: { open: '07:00', close: '16:00', isOpen: true },
      friday: { open: '07:00', close: '16:00', isOpen: true },
      saturday: { isOpen: false },
      sunday: { isOpen: false },
    },
    availability_status: 'available',
    years_in_business: 10,
    is_insured: 1,
    is_verified: 1,
    description: 'Bespoke carpentry and joinery for the modern workspace. Specializing in custom furniture, office fit-outs, and residential renovations.',
    website: 'https://techcitycarpentry.com',
  },
  {
    id: 'org_hoxton_handyman',
    name: 'Hoxton Handyman Services',
    email: 'info@hoxtonhandyman.co.uk',
    phone: '+44 20 7567 8901',
    categories: ['general_handyman', 'painting', 'carpentry'],
    service_radius_miles: 4,
    location: {
      address: '91 Hoxton Street',
      city: 'London',
      state: 'Greater London',
      zip: 'N1 6QL',
      coordinates: { latitude: 51.5312, longitude: -0.0765 },
    },
    accepts_new_requests: 1,
    total_completed: 312,
    response_time_avg_minutes: 30,
    opening_hours: {
      monday: { open: '07:00', close: '20:00', isOpen: true },
      tuesday: { open: '07:00', close: '20:00', isOpen: true },
      wednesday: { open: '07:00', close: '20:00', isOpen: true },
      thursday: { open: '07:00', close: '20:00', isOpen: true },
      friday: { open: '07:00', close: '20:00', isOpen: true },
      saturday: { open: '08:00', close: '18:00', isOpen: true },
      sunday: { open: '10:00', close: '16:00', isOpen: true },
    },
    availability_status: 'available',
    years_in_business: 18,
    is_insured: 1,
    is_verified: 1,
    description: 'Your local handyman for all odd jobs. No job too small! Fast response times and competitive rates. Available 7 days a week.',
    website: 'https://hoxtonhandyman.co.uk',
  },
  {
    id: 'org_clerkenwell_painting',
    name: 'Clerkenwell Painting & Decorating',
    email: 'team@clerkenwellpainting.com',
    phone: '+44 20 7678 9012',
    categories: ['painting'],
    service_radius_miles: 8,
    location: {
      address: '56 Clerkenwell Road',
      city: 'London',
      state: 'Greater London',
      zip: 'EC1M 5PX',
      coordinates: { latitude: 51.5221, longitude: -0.1065 },
    },
    accepts_new_requests: 1,
    total_completed: 98,
    response_time_avg_minutes: 180,
    opening_hours: {
      monday: { open: '09:00', close: '17:00', isOpen: true },
      tuesday: { open: '09:00', close: '17:00', isOpen: true },
      wednesday: { open: '09:00', close: '17:00', isOpen: true },
      thursday: { open: '09:00', close: '17:00', isOpen: true },
      friday: { open: '09:00', close: '17:00', isOpen: true },
      saturday: { isOpen: false },
      sunday: { isOpen: false },
    },
    availability_status: 'available',
    years_in_business: 6,
    is_insured: 1,
    is_verified: 0, // Not yet verified
    description: 'Professional painters and decorators. Specializing in interior design, period properties, and commercial spaces. Free quotes and color consultations.',
    website: 'https://clerkenwellpainting.com',
  },
  {
    id: 'org_cityroad_appliances',
    name: 'City Road Appliance Repair',
    email: 'repairs@cityroadappliances.co.uk',
    phone: '+44 20 7789 0123',
    categories: ['appliance_repair', 'electrical'],
    service_radius_miles: 5,
    location: {
      address: '134 City Road',
      city: 'London',
      state: 'Greater London',
      zip: 'EC1V 2NJ',
      coordinates: { latitude: 51.5283, longitude: -0.0889 },
    },
    accepts_new_requests: 1,
    total_completed: 223,
    response_time_avg_minutes: 75,
    opening_hours: {
      monday: { open: '08:00', close: '18:00', isOpen: true },
      tuesday: { open: '08:00', close: '18:00', isOpen: true },
      wednesday: { open: '08:00', close: '18:00', isOpen: true },
      thursday: { open: '08:00', close: '18:00', isOpen: true },
      friday: { open: '08:00', close: '18:00', isOpen: true },
      saturday: { open: '09:00', close: '13:00', isOpen: true },
      sunday: { isOpen: false },
    },
    availability_status: 'available',
    years_in_business: 14,
    is_insured: 1,
    is_verified: 1,
    description: 'Expert appliance repair for all major brands. Washing machines, dishwashers, fridges, ovens, and more. Same-day service available.',
    website: 'https://cityroadappliances.co.uk',
  },
  {
    id: 'org_oldstreet_247',
    name: 'Old Street 24/7 Emergency Services',
    email: 'emergency@oldstreet247.co.uk',
    phone: '+44 20 7890 1234',
    categories: ['plumbing', 'electrical', 'general_handyman'],
    service_radius_miles: 12,
    location: {
      address: '1 Old Street Roundabout',
      city: 'London',
      state: 'Greater London',
      zip: 'EC1V 9AA',
      coordinates: { latitude: 51.5254, longitude: -0.0877 },
    },
    accepts_new_requests: 1,
    total_completed: 567,
    response_time_avg_minutes: 15,
    opening_hours: {
      monday: { open: '00:00', close: '23:59', isOpen: true },
      tuesday: { open: '00:00', close: '23:59', isOpen: true },
      wednesday: { open: '00:00', close: '23:59', isOpen: true },
      thursday: { open: '00:00', close: '23:59', isOpen: true },
      friday: { open: '00:00', close: '23:59', isOpen: true },
      saturday: { open: '00:00', close: '23:59', isOpen: true },
      sunday: { open: '00:00', close: '23:59', isOpen: true },
    },
    availability_status: 'available',
    years_in_business: 20,
    is_insured: 1,
    is_verified: 1,
    description: '24/7 emergency response for plumbing, electrical, and general repairs. When disaster strikes, we\'re always available. Premium service with guaranteed response within 15 minutes.',
    website: 'https://oldstreet247.co.uk',
  },
];
